[2025-04-12T19:19:01.063+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-12T19:19:01.105+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_client_csv_to_delta.run_spark_submit manual__2025-04-12T19:18:59.406751+00:00 [queued]>
[2025-04-12T19:19:01.120+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_client_csv_to_delta.run_spark_submit manual__2025-04-12T19:18:59.406751+00:00 [queued]>
[2025-04-12T19:19:01.120+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-12T19:19:01.145+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_spark_submit> on 2025-04-12 19:18:59.406751+00:00
[2025-04-12T19:19:01.159+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3409) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-12T19:19:01.163+0000] {standard_task_runner.py:72} INFO - Started process 3410 to run task
[2025-04-12T19:19:01.164+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_client_csv_to_delta', 'run_spark_submit', 'manual__2025-04-12T19:18:59.406751+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/load_client_dags.py', '--cfg-path', '/tmp/tmpyivbsfb0']
[2025-04-12T19:19:01.168+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask run_spark_submit
[2025-04-12T19:19:01.278+0000] {task_command.py:467} INFO - Running <TaskInstance: load_client_csv_to_delta.run_spark_submit manual__2025-04-12T19:18:59.406751+00:00 [running]> on host a1eb074b5560
[2025-04-12T19:19:01.474+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_client_csv_to_delta' AIRFLOW_CTX_TASK_ID='run_spark_submit' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T19:18:59.406751+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-12T19:18:59.406751+00:00'
[2025-04-12T19:19:01.475+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-12T19:19:01.505+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-12T19:19:01.507+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n /opt/spark/bin/spark-submit   --master local[*]   --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension   --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog   --conf spark.jars=/opt/spark/jars/delta-spark_2.13-3.3.0.jar   /opt/***/dags/load_client_csv.py']
[2025-04-12T19:19:01.525+0000] {subprocess.py:99} INFO - Output:
[2025-04-12T19:19:05.689+0000] {subprocess.py:106} INFO - 25/04/12 19:19:05 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-04-12T19:19:06.220+0000] {subprocess.py:106} INFO - 25/04/12 19:19:06 WARN DependencyUtils: Local jar /opt/spark/jars/delta-spark_2.13-3.3.0.jar does not exist, skipping.
[2025-04-12T19:19:08.365+0000] {subprocess.py:106} INFO - 25/04/12 19:19:08 INFO SparkContext: Running Spark version 3.5.5
[2025-04-12T19:19:08.366+0000] {subprocess.py:106} INFO - 25/04/12 19:19:08 INFO SparkContext: OS info Linux, 6.8.0-1026-gcp, amd64
[2025-04-12T19:19:08.366+0000] {subprocess.py:106} INFO - 25/04/12 19:19:08 INFO SparkContext: Java version 17.0.14
[2025-04-12T19:19:08.462+0000] {subprocess.py:106} INFO - 25/04/12 19:19:08 INFO ResourceUtils: ==============================================================
[2025-04-12T19:19:08.463+0000] {subprocess.py:106} INFO - 25/04/12 19:19:08 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-04-12T19:19:08.464+0000] {subprocess.py:106} INFO - 25/04/12 19:19:08 INFO ResourceUtils: ==============================================================
[2025-04-12T19:19:08.464+0000] {subprocess.py:106} INFO - 25/04/12 19:19:08 INFO SparkContext: Submitted application: load_client_csv.py
[2025-04-12T19:19:08.509+0000] {subprocess.py:106} INFO - 25/04/12 19:19:08 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-04-12T19:19:08.530+0000] {subprocess.py:106} INFO - 25/04/12 19:19:08 INFO ResourceProfile: Limiting resource is cpu
[2025-04-12T19:19:08.537+0000] {subprocess.py:106} INFO - 25/04/12 19:19:08 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-04-12T19:19:08.653+0000] {subprocess.py:106} INFO - 25/04/12 19:19:08 INFO SecurityManager: Changing view acls to: default
[2025-04-12T19:19:08.654+0000] {subprocess.py:106} INFO - 25/04/12 19:19:08 INFO SecurityManager: Changing modify acls to: default
[2025-04-12T19:19:08.655+0000] {subprocess.py:106} INFO - 25/04/12 19:19:08 INFO SecurityManager: Changing view acls groups to:
[2025-04-12T19:19:08.658+0000] {subprocess.py:106} INFO - 25/04/12 19:19:08 INFO SecurityManager: Changing modify acls groups to:
[2025-04-12T19:19:08.658+0000] {subprocess.py:106} INFO - 25/04/12 19:19:08 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-04-12T19:19:09.218+0000] {subprocess.py:106} INFO - 25/04/12 19:19:09 INFO Utils: Successfully started service 'sparkDriver' on port 43679.
[2025-04-12T19:19:09.296+0000] {subprocess.py:106} INFO - 25/04/12 19:19:09 INFO SparkEnv: Registering MapOutputTracker
[2025-04-12T19:19:09.396+0000] {subprocess.py:106} INFO - 25/04/12 19:19:09 INFO SparkEnv: Registering BlockManagerMaster
[2025-04-12T19:19:09.423+0000] {subprocess.py:106} INFO - 25/04/12 19:19:09 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-04-12T19:19:09.424+0000] {subprocess.py:106} INFO - 25/04/12 19:19:09 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-04-12T19:19:09.429+0000] {subprocess.py:106} INFO - 25/04/12 19:19:09 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-04-12T19:19:09.469+0000] {subprocess.py:106} INFO - 25/04/12 19:19:09 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-2f97c5d7-48bb-425e-b370-f6c3b38d3a61
[2025-04-12T19:19:09.495+0000] {subprocess.py:106} INFO - 25/04/12 19:19:09 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-04-12T19:19:09.520+0000] {subprocess.py:106} INFO - 25/04/12 19:19:09 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-04-12T19:19:09.818+0000] {subprocess.py:106} INFO - 25/04/12 19:19:09 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-04-12T19:19:09.975+0000] {subprocess.py:106} INFO - 25/04/12 19:19:09 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-04-12T19:19:10.130+0000] {subprocess.py:106} INFO - 25/04/12 19:19:10 ERROR SparkContext: Failed to add file:/opt/spark/jars/delta-spark_2.13-3.3.0.jar to Spark environment
[2025-04-12T19:19:10.131+0000] {subprocess.py:106} INFO - java.io.FileNotFoundException: Jar /opt/spark/jars/delta-spark_2.13-3.3.0.jar not found
[2025-04-12T19:19:10.134+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:2095)
[2025-04-12T19:19:10.136+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2151)
[2025-04-12T19:19:10.138+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$15(SparkContext.scala:521)
[2025-04-12T19:19:10.140+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$15$adapted(SparkContext.scala:521)
[2025-04-12T19:19:10.141+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-04-12T19:19:10.142+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-04-12T19:19:10.145+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-04-12T19:19:10.145+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:521)
[2025-04-12T19:19:10.146+0000] {subprocess.py:106} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-04-12T19:19:10.147+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-04-12T19:19:10.148+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-04-12T19:19:10.151+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-04-12T19:19:10.153+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-04-12T19:19:10.154+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-04-12T19:19:10.155+0000] {subprocess.py:106} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-04-12T19:19:10.157+0000] {subprocess.py:106} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-04-12T19:19:10.158+0000] {subprocess.py:106} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2025-04-12T19:19:10.159+0000] {subprocess.py:106} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-04-12T19:19:10.163+0000] {subprocess.py:106} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-04-12T19:19:10.164+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-04-12T19:19:10.165+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-04-12T19:19:10.172+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-12T19:19:10.341+0000] {subprocess.py:106} INFO - 25/04/12 19:19:10 INFO Executor: Starting executor ID driver on host a1eb074b5560
[2025-04-12T19:19:10.345+0000] {subprocess.py:106} INFO - 25/04/12 19:19:10 INFO Executor: OS info Linux, 6.8.0-1026-gcp, amd64
[2025-04-12T19:19:10.348+0000] {subprocess.py:106} INFO - 25/04/12 19:19:10 INFO Executor: Java version 17.0.14
[2025-04-12T19:19:10.372+0000] {subprocess.py:106} INFO - 25/04/12 19:19:10 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-04-12T19:19:10.377+0000] {subprocess.py:106} INFO - 25/04/12 19:19:10 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@128aade1 for default.
[2025-04-12T19:19:10.515+0000] {subprocess.py:106} INFO - 25/04/12 19:19:10 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36335.
[2025-04-12T19:19:10.516+0000] {subprocess.py:106} INFO - 25/04/12 19:19:10 INFO NettyBlockTransferService: Server created on a1eb074b5560:36335
[2025-04-12T19:19:10.529+0000] {subprocess.py:106} INFO - 25/04/12 19:19:10 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-04-12T19:19:10.561+0000] {subprocess.py:106} INFO - 25/04/12 19:19:10 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, a1eb074b5560, 36335, None)
[2025-04-12T19:19:10.583+0000] {subprocess.py:106} INFO - 25/04/12 19:19:10 INFO BlockManagerMasterEndpoint: Registering block manager a1eb074b5560:36335 with 434.4 MiB RAM, BlockManagerId(driver, a1eb074b5560, 36335, None)
[2025-04-12T19:19:10.590+0000] {subprocess.py:106} INFO - 25/04/12 19:19:10 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, a1eb074b5560, 36335, None)
[2025-04-12T19:19:10.597+0000] {subprocess.py:106} INFO - 25/04/12 19:19:10 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, a1eb074b5560, 36335, None)
[2025-04-12T19:19:12.043+0000] {subprocess.py:106} INFO - 25/04/12 19:19:12 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-04-12T19:19:12.048+0000] {subprocess.py:106} INFO - 25/04/12 19:19:12 INFO SharedState: Warehouse path is 'file:/tmp/***tmpa1zqfeo2/spark-warehouse'.
[2025-04-12T19:19:15.305+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-04-12T19:19:15.306+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/load_client_csv.py", line 43, in <module>
[2025-04-12T19:19:15.307+0000] {subprocess.py:106} INFO -     df = load_client_csv(file_path)
[2025-04-12T19:19:15.311+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-12T19:19:15.312+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/load_client_csv.py", line 18, in load_client_csv
[2025-04-12T19:19:15.313+0000] {subprocess.py:106} INFO -     df = spark.read.csv(file_path, header=True, inferSchema=True)
[2025-04-12T19:19:15.315+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-12T19:19:15.316+0000] {subprocess.py:106} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-04-12T19:19:15.317+0000] {subprocess.py:106} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-04-12T19:19:15.317+0000] {subprocess.py:106} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-04-12T19:19:15.340+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/files/clients.csv.
[2025-04-12T19:19:15.466+0000] {subprocess.py:106} INFO - 25/04/12 19:19:15 INFO SparkContext: Invoking stop() from shutdown hook
[2025-04-12T19:19:15.468+0000] {subprocess.py:106} INFO - 25/04/12 19:19:15 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-04-12T19:19:15.486+0000] {subprocess.py:106} INFO - 25/04/12 19:19:15 INFO SparkUI: Stopped Spark web UI at http://a1eb074b5560:4040
[2025-04-12T19:19:15.513+0000] {subprocess.py:106} INFO - 25/04/12 19:19:15 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-04-12T19:19:15.540+0000] {subprocess.py:106} INFO - 25/04/12 19:19:15 INFO MemoryStore: MemoryStore cleared
[2025-04-12T19:19:15.545+0000] {subprocess.py:106} INFO - 25/04/12 19:19:15 INFO BlockManager: BlockManager stopped
[2025-04-12T19:19:15.556+0000] {subprocess.py:106} INFO - 25/04/12 19:19:15 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-04-12T19:19:15.566+0000] {subprocess.py:106} INFO - 25/04/12 19:19:15 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-04-12T19:19:15.582+0000] {subprocess.py:106} INFO - 25/04/12 19:19:15 INFO SparkContext: Successfully stopped SparkContext
[2025-04-12T19:19:15.585+0000] {subprocess.py:106} INFO - 25/04/12 19:19:15 INFO ShutdownHookManager: Shutdown hook called
[2025-04-12T19:19:15.586+0000] {subprocess.py:106} INFO - 25/04/12 19:19:15 INFO ShutdownHookManager: Deleting directory /tmp/spark-def84975-e747-437d-bfa9-817e11c4b3e9
[2025-04-12T19:19:15.598+0000] {subprocess.py:106} INFO - 25/04/12 19:19:15 INFO ShutdownHookManager: Deleting directory /tmp/spark-bf9c3329-104a-4b51-b1dc-7243a88404f8
[2025-04-12T19:19:15.607+0000] {subprocess.py:106} INFO - 25/04/12 19:19:15 INFO ShutdownHookManager: Deleting directory /tmp/spark-bf9c3329-104a-4b51-b1dc-7243a88404f8/pyspark-dd9a0c3a-fee0-4937-82fb-57a47f92f3b4
[2025-04-12T19:19:15.701+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-12T19:19:15.730+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-12T19:19:15.740+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=load_client_csv_to_delta, task_id=run_spark_submit, run_id=manual__2025-04-12T19:18:59.406751+00:00, execution_date=20250412T191859, start_date=20250412T191901, end_date=20250412T191915
[2025-04-12T19:19:15.767+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-12T19:19:15.768+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task run_spark_submit (Bash command failed. The command returned a non-zero exit code 1.; 3410)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-12T19:19:15.810+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-12T19:19:15.846+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-12T19:19:15.849+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
