[2025-04-12T19:36:59.484+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-12T19:36:59.527+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_client_csv_to_delta.run_spark_submit manual__2025-04-12T19:36:57.262451+00:00 [queued]>
[2025-04-12T19:36:59.547+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_client_csv_to_delta.run_spark_submit manual__2025-04-12T19:36:57.262451+00:00 [queued]>
[2025-04-12T19:36:59.548+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-12T19:36:59.571+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_spark_submit> on 2025-04-12 19:36:57.262451+00:00
[2025-04-12T19:36:59.583+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=108) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-12T19:36:59.587+0000] {standard_task_runner.py:72} INFO - Started process 109 to run task
[2025-04-12T19:36:59.589+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_client_csv_to_delta', 'run_spark_submit', 'manual__2025-04-12T19:36:57.262451+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/load_client_dags.py', '--cfg-path', '/tmp/tmpv1lrv8ds']
[2025-04-12T19:36:59.592+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask run_spark_submit
[2025-04-12T19:36:59.723+0000] {task_command.py:467} INFO - Running <TaskInstance: load_client_csv_to_delta.run_spark_submit manual__2025-04-12T19:36:57.262451+00:00 [running]> on host e855ddfaafd5
[2025-04-12T19:36:59.880+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_client_csv_to_delta' AIRFLOW_CTX_TASK_ID='run_spark_submit' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T19:36:57.262451+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-12T19:36:57.262451+00:00'
[2025-04-12T19:36:59.881+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-12T19:36:59.954+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-12T19:36:59.955+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n /opt/spark/bin/spark-submit   --master local[*]   --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension   --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog   --conf spark.jars=/opt/spark/jars/delta-spark_2.13-3.3.0.jar   /opt/***/dags/load_client_csv.py']
[2025-04-12T19:36:59.974+0000] {subprocess.py:99} INFO - Output:
[2025-04-12T19:37:00.010+0000] {subprocess.py:106} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-04-12T19:37:06.334+0000] {subprocess.py:106} INFO - 25/04/12 19:37:06 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-04-12T19:37:07.205+0000] {subprocess.py:106} INFO - 25/04/12 19:37:07 WARN DependencyUtils: Local jar /opt/spark/jars/delta-spark_2.13-3.3.0.jar does not exist, skipping.
[2025-04-12T19:37:12.707+0000] {subprocess.py:106} INFO - 25/04/12 19:37:12 INFO SparkContext: Running Spark version 3.5.5
[2025-04-12T19:37:12.708+0000] {subprocess.py:106} INFO - 25/04/12 19:37:12 INFO SparkContext: OS info Linux, 6.8.0-1026-gcp, amd64
[2025-04-12T19:37:12.716+0000] {subprocess.py:106} INFO - 25/04/12 19:37:12 INFO SparkContext: Java version 17.0.14
[2025-04-12T19:37:12.949+0000] {subprocess.py:106} INFO - 25/04/12 19:37:12 INFO ResourceUtils: ==============================================================
[2025-04-12T19:37:12.950+0000] {subprocess.py:106} INFO - 25/04/12 19:37:12 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-04-12T19:37:12.961+0000] {subprocess.py:106} INFO - 25/04/12 19:37:12 INFO ResourceUtils: ==============================================================
[2025-04-12T19:37:12.964+0000] {subprocess.py:106} INFO - 25/04/12 19:37:12 INFO SparkContext: Submitted application: load_client_csv.py
[2025-04-12T19:37:13.110+0000] {subprocess.py:106} INFO - 25/04/12 19:37:13 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-04-12T19:37:13.189+0000] {subprocess.py:106} INFO - 25/04/12 19:37:13 INFO ResourceProfile: Limiting resource is cpu
[2025-04-12T19:37:13.206+0000] {subprocess.py:106} INFO - 25/04/12 19:37:13 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-04-12T19:37:13.836+0000] {subprocess.py:106} INFO - 25/04/12 19:37:13 INFO SecurityManager: Changing view acls to: default
[2025-04-12T19:37:13.837+0000] {subprocess.py:106} INFO - 25/04/12 19:37:13 INFO SecurityManager: Changing modify acls to: default
[2025-04-12T19:37:13.851+0000] {subprocess.py:106} INFO - 25/04/12 19:37:13 INFO SecurityManager: Changing view acls groups to:
[2025-04-12T19:37:13.854+0000] {subprocess.py:106} INFO - 25/04/12 19:37:13 INFO SecurityManager: Changing modify acls groups to:
[2025-04-12T19:37:13.870+0000] {subprocess.py:106} INFO - 25/04/12 19:37:13 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-04-12T19:37:15.530+0000] {subprocess.py:106} INFO - 25/04/12 19:37:15 INFO Utils: Successfully started service 'sparkDriver' on port 35741.
[2025-04-12T19:37:15.864+0000] {subprocess.py:106} INFO - 25/04/12 19:37:15 INFO SparkEnv: Registering MapOutputTracker
[2025-04-12T19:37:16.237+0000] {subprocess.py:106} INFO - 25/04/12 19:37:16 INFO SparkEnv: Registering BlockManagerMaster
[2025-04-12T19:37:16.393+0000] {subprocess.py:106} INFO - 25/04/12 19:37:16 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-04-12T19:37:16.396+0000] {subprocess.py:106} INFO - 25/04/12 19:37:16 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-04-12T19:37:16.427+0000] {subprocess.py:106} INFO - 25/04/12 19:37:16 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-04-12T19:37:16.622+0000] {subprocess.py:106} INFO - 25/04/12 19:37:16 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-d600ae9a-a3c2-4a80-a6ad-583913f0f0d1
[2025-04-12T19:37:16.707+0000] {subprocess.py:106} INFO - 25/04/12 19:37:16 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-04-12T19:37:16.855+0000] {subprocess.py:106} INFO - 25/04/12 19:37:16 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-04-12T19:37:18.178+0000] {subprocess.py:106} INFO - 25/04/12 19:37:18 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-04-12T19:37:18.532+0000] {subprocess.py:106} INFO - 25/04/12 19:37:18 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-04-12T19:37:18.708+0000] {subprocess.py:106} INFO - 25/04/12 19:37:18 ERROR SparkContext: Failed to add file:/opt/spark/jars/delta-spark_2.13-3.3.0.jar to Spark environment
[2025-04-12T19:37:18.709+0000] {subprocess.py:106} INFO - java.io.FileNotFoundException: Jar /opt/spark/jars/delta-spark_2.13-3.3.0.jar not found
[2025-04-12T19:37:18.710+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:2095)
[2025-04-12T19:37:18.710+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2151)
[2025-04-12T19:37:18.711+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$15(SparkContext.scala:521)
[2025-04-12T19:37:18.713+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$15$adapted(SparkContext.scala:521)
[2025-04-12T19:37:18.716+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-04-12T19:37:18.717+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-04-12T19:37:18.718+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-04-12T19:37:18.718+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:521)
[2025-04-12T19:37:18.719+0000] {subprocess.py:106} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-04-12T19:37:18.719+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-04-12T19:37:18.720+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-04-12T19:37:18.721+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-04-12T19:37:18.721+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-04-12T19:37:18.722+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-04-12T19:37:18.722+0000] {subprocess.py:106} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-04-12T19:37:18.723+0000] {subprocess.py:106} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-04-12T19:37:18.723+0000] {subprocess.py:106} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2025-04-12T19:37:18.724+0000] {subprocess.py:106} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-04-12T19:37:18.724+0000] {subprocess.py:106} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-04-12T19:37:18.725+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-04-12T19:37:18.725+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-04-12T19:37:18.726+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-12T19:37:18.998+0000] {subprocess.py:106} INFO - 25/04/12 19:37:18 INFO Executor: Starting executor ID driver on host e855ddfaafd5
[2025-04-12T19:37:19.001+0000] {subprocess.py:106} INFO - 25/04/12 19:37:18 INFO Executor: OS info Linux, 6.8.0-1026-gcp, amd64
[2025-04-12T19:37:19.002+0000] {subprocess.py:106} INFO - 25/04/12 19:37:19 INFO Executor: Java version 17.0.14
[2025-04-12T19:37:19.034+0000] {subprocess.py:106} INFO - 25/04/12 19:37:19 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-04-12T19:37:19.035+0000] {subprocess.py:106} INFO - 25/04/12 19:37:19 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@128aade1 for default.
[2025-04-12T19:37:19.135+0000] {subprocess.py:106} INFO - 25/04/12 19:37:19 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 42649.
[2025-04-12T19:37:19.136+0000] {subprocess.py:106} INFO - 25/04/12 19:37:19 INFO NettyBlockTransferService: Server created on e855ddfaafd5:42649
[2025-04-12T19:37:19.148+0000] {subprocess.py:106} INFO - 25/04/12 19:37:19 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-04-12T19:37:19.166+0000] {subprocess.py:106} INFO - 25/04/12 19:37:19 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, e855ddfaafd5, 42649, None)
[2025-04-12T19:37:19.180+0000] {subprocess.py:106} INFO - 25/04/12 19:37:19 INFO BlockManagerMasterEndpoint: Registering block manager e855ddfaafd5:42649 with 434.4 MiB RAM, BlockManagerId(driver, e855ddfaafd5, 42649, None)
[2025-04-12T19:37:19.191+0000] {subprocess.py:106} INFO - 25/04/12 19:37:19 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, e855ddfaafd5, 42649, None)
[2025-04-12T19:37:19.196+0000] {subprocess.py:106} INFO - 25/04/12 19:37:19 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, e855ddfaafd5, 42649, None)
[2025-04-12T19:37:20.644+0000] {subprocess.py:106} INFO - 25/04/12 19:37:20 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-04-12T19:37:20.651+0000] {subprocess.py:106} INFO - 25/04/12 19:37:20 INFO SharedState: Warehouse path is 'file:/tmp/***tmp36bfhpik/spark-warehouse'.
[2025-04-12T19:37:23.083+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-04-12T19:37:23.084+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/load_client_csv.py", line 43, in <module>
[2025-04-12T19:37:23.086+0000] {subprocess.py:106} INFO -     df = load_client_csv(file_path)
[2025-04-12T19:37:23.086+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-12T19:37:23.087+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/load_client_csv.py", line 18, in load_client_csv
[2025-04-12T19:37:23.090+0000] {subprocess.py:106} INFO -     df = spark.read.csv(file_path, header=True, inferSchema=True)
[2025-04-12T19:37:23.090+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-12T19:37:23.091+0000] {subprocess.py:106} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-04-12T19:37:23.091+0000] {subprocess.py:106} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-04-12T19:37:23.094+0000] {subprocess.py:106} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-04-12T19:37:23.100+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/opt/***/files/clients.csv.
[2025-04-12T19:37:23.189+0000] {subprocess.py:106} INFO - 25/04/12 19:37:23 INFO SparkContext: Invoking stop() from shutdown hook
[2025-04-12T19:37:23.192+0000] {subprocess.py:106} INFO - 25/04/12 19:37:23 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-04-12T19:37:23.210+0000] {subprocess.py:106} INFO - 25/04/12 19:37:23 INFO SparkUI: Stopped Spark web UI at http://e855ddfaafd5:4040
[2025-04-12T19:37:23.236+0000] {subprocess.py:106} INFO - 25/04/12 19:37:23 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-04-12T19:37:23.262+0000] {subprocess.py:106} INFO - 25/04/12 19:37:23 INFO MemoryStore: MemoryStore cleared
[2025-04-12T19:37:23.263+0000] {subprocess.py:106} INFO - 25/04/12 19:37:23 INFO BlockManager: BlockManager stopped
[2025-04-12T19:37:23.273+0000] {subprocess.py:106} INFO - 25/04/12 19:37:23 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-04-12T19:37:23.281+0000] {subprocess.py:106} INFO - 25/04/12 19:37:23 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-04-12T19:37:23.300+0000] {subprocess.py:106} INFO - 25/04/12 19:37:23 INFO SparkContext: Successfully stopped SparkContext
[2025-04-12T19:37:23.301+0000] {subprocess.py:106} INFO - 25/04/12 19:37:23 INFO ShutdownHookManager: Shutdown hook called
[2025-04-12T19:37:23.304+0000] {subprocess.py:106} INFO - 25/04/12 19:37:23 INFO ShutdownHookManager: Deleting directory /tmp/spark-6b598e1c-bf27-4da9-946d-747dcacdb2e3
[2025-04-12T19:37:23.315+0000] {subprocess.py:106} INFO - 25/04/12 19:37:23 INFO ShutdownHookManager: Deleting directory /tmp/spark-ee256da1-f2dd-41a0-b8f3-9bd5ec1d19df
[2025-04-12T19:37:23.327+0000] {subprocess.py:106} INFO - 25/04/12 19:37:23 INFO ShutdownHookManager: Deleting directory /tmp/spark-ee256da1-f2dd-41a0-b8f3-9bd5ec1d19df/pyspark-da98bbdf-6b52-4d87-927d-00fc26daabd4
[2025-04-12T19:37:23.399+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-12T19:37:23.424+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-12T19:37:23.432+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=load_client_csv_to_delta, task_id=run_spark_submit, run_id=manual__2025-04-12T19:36:57.262451+00:00, execution_date=20250412T193657, start_date=20250412T193659, end_date=20250412T193723
[2025-04-12T19:37:23.452+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-12T19:37:23.454+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task run_spark_submit (Bash command failed. The command returned a non-zero exit code 1.; 109)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-12T19:37:23.486+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-12T19:37:23.527+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-12T19:37:23.529+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
