[2025-04-13T03:44:46.224+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T03:44:46.306+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_client_csv_to_delta.run_spark_submit manual__2025-04-13T03:44:40.336011+00:00 [queued]>
[2025-04-13T03:44:46.340+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_client_csv_to_delta.run_spark_submit manual__2025-04-13T03:44:40.336011+00:00 [queued]>
[2025-04-13T03:44:46.341+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-13T03:44:46.407+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_spark_submit> on 2025-04-13 03:44:40.336011+00:00
[2025-04-13T03:44:46.439+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=203) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T03:44:46.448+0000] {standard_task_runner.py:72} INFO - Started process 204 to run task
[2025-04-13T03:44:46.467+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_client_csv_to_delta', 'run_spark_submit', 'manual__2025-04-13T03:44:40.336011+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/load_client_dags.py', '--cfg-path', '/tmp/tmpvr_xapxx']
[2025-04-13T03:44:46.476+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask run_spark_submit
[2025-04-13T03:44:46.670+0000] {task_command.py:467} INFO - Running <TaskInstance: load_client_csv_to_delta.run_spark_submit manual__2025-04-13T03:44:40.336011+00:00 [running]> on host 9e3b1470c034
[2025-04-13T03:44:47.112+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_client_csv_to_delta' AIRFLOW_CTX_TASK_ID='run_spark_submit' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T03:44:40.336011+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-13T03:44:40.336011+00:00'
[2025-04-13T03:44:47.120+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-13T03:44:47.350+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-13T03:44:47.356+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n /opt/spark/bin/spark-submit   --master local[*]   --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension   --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog   --jars /opt/spark/jar/delta-spark_2.13-3.3.0.jar,/opt/spark/jar/delta-storage-3.3.0.jar   /opt/***/dags/load_client_csv.py']
[2025-04-13T03:44:47.404+0000] {subprocess.py:99} INFO - Output:
[2025-04-13T03:44:47.490+0000] {subprocess.py:106} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-04-13T03:44:56.618+0000] {subprocess.py:106} INFO - 25/04/13 03:44:56 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-04-13T03:44:57.746+0000] {subprocess.py:106} INFO - 25/04/13 03:44:57 WARN DependencyUtils: Local jar /opt/spark/jar/delta-spark_2.13-3.3.0.jar does not exist, skipping.
[2025-04-13T03:44:57.749+0000] {subprocess.py:106} INFO - 25/04/13 03:44:57 WARN DependencyUtils: Local jar /opt/spark/jar/delta-storage-3.3.0.jar does not exist, skipping.
[2025-04-13T03:45:02.020+0000] {subprocess.py:106} INFO - 25/04/13 03:45:02 INFO SparkContext: Running Spark version 3.5.5
[2025-04-13T03:45:02.021+0000] {subprocess.py:106} INFO - 25/04/13 03:45:02 INFO SparkContext: OS info Linux, 6.8.0-1026-gcp, amd64
[2025-04-13T03:45:02.023+0000] {subprocess.py:106} INFO - 25/04/13 03:45:02 INFO SparkContext: Java version 17.0.14
[2025-04-13T03:45:02.210+0000] {subprocess.py:106} INFO - 25/04/13 03:45:02 INFO ResourceUtils: ==============================================================
[2025-04-13T03:45:02.213+0000] {subprocess.py:106} INFO - 25/04/13 03:45:02 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-04-13T03:45:02.216+0000] {subprocess.py:106} INFO - 25/04/13 03:45:02 INFO ResourceUtils: ==============================================================
[2025-04-13T03:45:02.217+0000] {subprocess.py:106} INFO - 25/04/13 03:45:02 INFO SparkContext: Submitted application: load_client_csv.py
[2025-04-13T03:45:02.331+0000] {subprocess.py:106} INFO - 25/04/13 03:45:02 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-04-13T03:45:02.356+0000] {subprocess.py:106} INFO - 25/04/13 03:45:02 INFO ResourceProfile: Limiting resource is cpu
[2025-04-13T03:45:02.358+0000] {subprocess.py:106} INFO - 25/04/13 03:45:02 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-04-13T03:45:02.708+0000] {subprocess.py:106} INFO - 25/04/13 03:45:02 INFO SecurityManager: Changing view acls to: default
[2025-04-13T03:45:02.709+0000] {subprocess.py:106} INFO - 25/04/13 03:45:02 INFO SecurityManager: Changing modify acls to: default
[2025-04-13T03:45:02.716+0000] {subprocess.py:106} INFO - 25/04/13 03:45:02 INFO SecurityManager: Changing view acls groups to:
[2025-04-13T03:45:02.717+0000] {subprocess.py:106} INFO - 25/04/13 03:45:02 INFO SecurityManager: Changing modify acls groups to:
[2025-04-13T03:45:02.722+0000] {subprocess.py:106} INFO - 25/04/13 03:45:02 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-04-13T03:45:03.851+0000] {subprocess.py:106} INFO - 25/04/13 03:45:03 INFO Utils: Successfully started service 'sparkDriver' on port 36635.
[2025-04-13T03:45:03.984+0000] {subprocess.py:106} INFO - 25/04/13 03:45:03 INFO SparkEnv: Registering MapOutputTracker
[2025-04-13T03:45:04.190+0000] {subprocess.py:106} INFO - 25/04/13 03:45:04 INFO SparkEnv: Registering BlockManagerMaster
[2025-04-13T03:45:04.308+0000] {subprocess.py:106} INFO - 25/04/13 03:45:04 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-04-13T03:45:04.314+0000] {subprocess.py:106} INFO - 25/04/13 03:45:04 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-04-13T03:45:04.341+0000] {subprocess.py:106} INFO - 25/04/13 03:45:04 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-04-13T03:45:04.480+0000] {subprocess.py:106} INFO - 25/04/13 03:45:04 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-776683ab-80db-484d-be4d-1ccdbff75bb3
[2025-04-13T03:45:04.598+0000] {subprocess.py:106} INFO - 25/04/13 03:45:04 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-04-13T03:45:04.668+0000] {subprocess.py:106} INFO - 25/04/13 03:45:04 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-04-13T03:45:05.342+0000] {subprocess.py:106} INFO - 25/04/13 03:45:05 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-04-13T03:45:06.111+0000] {subprocess.py:106} INFO - 25/04/13 03:45:06 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-04-13T03:45:06.147+0000] {subprocess.py:106} INFO - 25/04/13 03:45:06 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2025-04-13T03:45:06.400+0000] {subprocess.py:106} INFO - 25/04/13 03:45:06 ERROR SparkContext: Failed to add file:/opt/spark/jar/delta-spark_2.13-3.3.0.jar to Spark environment
[2025-04-13T03:45:06.401+0000] {subprocess.py:106} INFO - java.io.FileNotFoundException: Jar /opt/spark/jar/delta-spark_2.13-3.3.0.jar not found
[2025-04-13T03:45:06.408+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:2095)
[2025-04-13T03:45:06.409+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2151)
[2025-04-13T03:45:06.416+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$15(SparkContext.scala:521)
[2025-04-13T03:45:06.417+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$15$adapted(SparkContext.scala:521)
[2025-04-13T03:45:06.419+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-04-13T03:45:06.420+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-04-13T03:45:06.425+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-04-13T03:45:06.432+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:521)
[2025-04-13T03:45:06.433+0000] {subprocess.py:106} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-04-13T03:45:06.450+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-04-13T03:45:06.472+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-04-13T03:45:06.473+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-04-13T03:45:06.490+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-04-13T03:45:06.490+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-04-13T03:45:06.491+0000] {subprocess.py:106} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-04-13T03:45:06.501+0000] {subprocess.py:106} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-04-13T03:45:06.507+0000] {subprocess.py:106} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2025-04-13T03:45:06.509+0000] {subprocess.py:106} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-04-13T03:45:06.519+0000] {subprocess.py:106} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-04-13T03:45:06.520+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-04-13T03:45:06.524+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-04-13T03:45:06.525+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-13T03:45:06.534+0000] {subprocess.py:106} INFO - 25/04/13 03:45:06 ERROR SparkContext: Failed to add file:/opt/spark/jar/delta-storage-3.3.0.jar to Spark environment
[2025-04-13T03:45:06.538+0000] {subprocess.py:106} INFO - java.io.FileNotFoundException: Jar /opt/spark/jar/delta-storage-3.3.0.jar not found
[2025-04-13T03:45:06.545+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:2095)
[2025-04-13T03:45:06.552+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2151)
[2025-04-13T03:45:06.560+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$15(SparkContext.scala:521)
[2025-04-13T03:45:06.584+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$15$adapted(SparkContext.scala:521)
[2025-04-13T03:45:06.596+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-04-13T03:45:06.597+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-04-13T03:45:06.622+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-04-13T03:45:06.623+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:521)
[2025-04-13T03:45:06.637+0000] {subprocess.py:106} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-04-13T03:45:06.638+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-04-13T03:45:06.639+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-04-13T03:45:06.643+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-04-13T03:45:06.654+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-04-13T03:45:06.655+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-04-13T03:45:06.656+0000] {subprocess.py:106} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-04-13T03:45:06.667+0000] {subprocess.py:106} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-04-13T03:45:06.667+0000] {subprocess.py:106} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2025-04-13T03:45:06.668+0000] {subprocess.py:106} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-04-13T03:45:06.685+0000] {subprocess.py:106} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-04-13T03:45:06.686+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-04-13T03:45:06.700+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-04-13T03:45:06.711+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-13T03:45:07.017+0000] {subprocess.py:106} INFO - 25/04/13 03:45:07 INFO Executor: Starting executor ID driver on host 9e3b1470c034
[2025-04-13T03:45:07.029+0000] {subprocess.py:106} INFO - 25/04/13 03:45:07 INFO Executor: OS info Linux, 6.8.0-1026-gcp, amd64
[2025-04-13T03:45:07.032+0000] {subprocess.py:106} INFO - 25/04/13 03:45:07 INFO Executor: Java version 17.0.14
[2025-04-13T03:45:07.078+0000] {subprocess.py:106} INFO - 25/04/13 03:45:07 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-04-13T03:45:07.085+0000] {subprocess.py:106} INFO - 25/04/13 03:45:07 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@75d767a4 for default.
[2025-04-13T03:45:07.202+0000] {subprocess.py:106} INFO - 25/04/13 03:45:07 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 33017.
[2025-04-13T03:45:07.203+0000] {subprocess.py:106} INFO - 25/04/13 03:45:07 INFO NettyBlockTransferService: Server created on 9e3b1470c034:33017
[2025-04-13T03:45:07.209+0000] {subprocess.py:106} INFO - 25/04/13 03:45:07 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-04-13T03:45:07.229+0000] {subprocess.py:106} INFO - 25/04/13 03:45:07 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 9e3b1470c034, 33017, None)
[2025-04-13T03:45:07.259+0000] {subprocess.py:106} INFO - 25/04/13 03:45:07 INFO BlockManagerMasterEndpoint: Registering block manager 9e3b1470c034:33017 with 434.4 MiB RAM, BlockManagerId(driver, 9e3b1470c034, 33017, None)
[2025-04-13T03:45:07.273+0000] {subprocess.py:106} INFO - 25/04/13 03:45:07 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 9e3b1470c034, 33017, None)
[2025-04-13T03:45:07.283+0000] {subprocess.py:106} INFO - 25/04/13 03:45:07 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 9e3b1470c034, 33017, None)
[2025-04-13T03:45:09.705+0000] {subprocess.py:106} INFO - 25/04/13 03:45:09 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-04-13T03:45:09.721+0000] {subprocess.py:106} INFO - 25/04/13 03:45:09 INFO SharedState: Warehouse path is 'file:/tmp/***tmpb45wlj4b/spark-warehouse'.
[2025-04-13T03:45:19.141+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-04-13T03:45:19.142+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/load_client_csv.py", line 46, in <module>
[2025-04-13T03:45:19.150+0000] {subprocess.py:106} INFO -     df = load_client_csv(file_path)
[2025-04-13T03:45:19.158+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-13T03:45:19.164+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/load_client_csv.py", line 21, in load_client_csv
[2025-04-13T03:45:19.169+0000] {subprocess.py:106} INFO -     df = spark.read.csv(file_path, header=True, inferSchema=True)
[2025-04-13T03:45:19.170+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-13T03:45:19.185+0000] {subprocess.py:106} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-04-13T03:45:19.198+0000] {subprocess.py:106} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-04-13T03:45:19.200+0000] {subprocess.py:106} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-04-13T03:45:19.289+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/opt/***/files/transactions/clients.csv.
[2025-04-13T03:45:19.951+0000] {subprocess.py:106} INFO - 25/04/13 03:45:19 INFO SparkContext: Invoking stop() from shutdown hook
[2025-04-13T03:45:19.952+0000] {subprocess.py:106} INFO - 25/04/13 03:45:19 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-04-13T03:45:20.035+0000] {subprocess.py:106} INFO - 25/04/13 03:45:20 INFO SparkUI: Stopped Spark web UI at http://9e3b1470c034:4041
[2025-04-13T03:45:20.166+0000] {subprocess.py:106} INFO - 25/04/13 03:45:20 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-04-13T03:45:20.295+0000] {subprocess.py:106} INFO - 25/04/13 03:45:20 INFO MemoryStore: MemoryStore cleared
[2025-04-13T03:45:20.305+0000] {subprocess.py:106} INFO - 25/04/13 03:45:20 INFO BlockManager: BlockManager stopped
[2025-04-13T03:45:20.355+0000] {subprocess.py:106} INFO - 25/04/13 03:45:20 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-04-13T03:45:20.447+0000] {subprocess.py:106} INFO - 25/04/13 03:45:20 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-04-13T03:45:20.577+0000] {subprocess.py:106} INFO - 25/04/13 03:45:20 INFO SparkContext: Successfully stopped SparkContext
[2025-04-13T03:45:20.589+0000] {subprocess.py:106} INFO - 25/04/13 03:45:20 INFO ShutdownHookManager: Shutdown hook called
[2025-04-13T03:45:20.623+0000] {subprocess.py:106} INFO - 25/04/13 03:45:20 INFO ShutdownHookManager: Deleting directory /tmp/spark-778da19e-1358-49cf-8a6c-a0767851ff13/pyspark-e4060da9-f2f1-4db7-aadf-10fed2075bb3
[2025-04-13T03:45:20.651+0000] {subprocess.py:106} INFO - 25/04/13 03:45:20 INFO ShutdownHookManager: Deleting directory /tmp/spark-f8042466-d892-4034-bb40-23ae6c72058e
[2025-04-13T03:45:20.675+0000] {subprocess.py:106} INFO - 25/04/13 03:45:20 INFO ShutdownHookManager: Deleting directory /tmp/spark-778da19e-1358-49cf-8a6c-a0767851ff13
[2025-04-13T03:45:21.087+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-13T03:45:21.243+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-13T03:45:21.330+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=load_client_csv_to_delta, task_id=run_spark_submit, run_id=manual__2025-04-13T03:44:40.336011+00:00, execution_date=20250413T034440, start_date=20250413T034446, end_date=20250413T034521
[2025-04-13T03:45:21.464+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-13T03:45:21.470+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task run_spark_submit (Bash command failed. The command returned a non-zero exit code 1.; 204)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-13T03:45:21.580+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-13T03:45:21.678+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-13T03:45:21.684+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
